remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed

favicon: assets/favicon.ico

title: "music demixer"

# dont mess with SEO here
description: "Do it all with our cutting-edge AI tool: separate songs, split stems, instrumental breakdowns, vocal remover, isolate vocals, extract instruments, create karaoke tracks, and more."
keywords:
  - vocal remover
  - extract vocals
  - isolate vocals
  - separate music
  - instrumental breakdown
  - karaoke songs
  - music demixing
  - stem separation
  - AI music tool
  - free music demixer
  - Demucs
  - Transformer AI
  - browser-based music tool
  - Android music app
  - private music separation
  - unlimited music splitting

url: "https://freemusicdemixer.com"

author: "sevagh"

logo: "/assets/images/logo.webp"

social:
  name: Sevag H
  links:
    - https://github.com/sevagh

google_analytics: 'G-B0BF5H94FM'
future: false
