# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'jekyll-sitemap', group: :jekyll_plugins
gem 'jekyll-feed', group: :jekyll_plugins
gem 'jekyll-seo-tag', group: :jekyll_plugins
gem 'jekyll', group: :jekyll_plugins
gem 'webrick'
gem 'netrc'
gem 'kramdown-parser-gfm'
gem 'nokogiri'
